# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 22:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import urlcutsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('urlcutsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_id',
            field=models.SlugField(default=urlcutsite.models.Url._url_id, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='url',
            name='submitter',
            field=models.ForeignKey(default=urlcutsite.models.Url._random_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
